version: "3.8"
services:
    react-app:
      build:
        context: .
        dockerfile: Dockerfile
      image: lucifer666coder/react-app
      stdin_open: true
      ports:
        - 7000:7000
      networks:
        - mern-app

networks:
  mern-app:
    driver: bridge